### ISSUE TITLE
ERROR:  import SetCreds from "../lib/index.js"

### ISSUE THREAD

**Issue by ToMMy86** [PredictMobile/aws-sso-credentials-getter#6]
Hello, 
First of all thank you for sharing this gr8 utility, i'm facing a problem on my ubuntu on WSL2 ( i'm not familiar with nodejs ) 

sudo apt intall npm
npm install -g aws-sso-credentials-getter

getting this: 

▶ ssocred  TestProfile
/usr/local/lib/node_modules/aws-sso-credentials-getter/bin/index.js:9
import SetCreds from "../lib/index.js"
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
    
    ▶ npm --version
6.14.4
    
    The SSO Profile is configured with AWS CLI and is working ok .
    
    Any clue ? Thank you

**Comment by ToMMy86** [comment]
Ok managed to get it working 

If you user  Ubuntu on WSL2 , install  nodejs  with PPA.
